### ISSUE TITLE
ajout d'une application mobile au dossier apps

### ISSUE THREAD

**Issue by LouisLec** [GRINN-dev/template#1]
# Initialisation de l'app mobile

## Objectif
Avoir une application mobile dans notre monorepo, qui se lance et s'installe en meme temps que le reste

## Détails
Application React Native + Expo, créée en ajoutant un dossier `expo` dans `apps`, en se déplaçant dedans et en lancant `npx create-expo-app@latest`

**Comment by NinonMaraval** [comment]
![simulator_screenshot_3FA5881F-FE17-4352-B3F7-E9FC8ECC45C5](https://github.com/user-attachments/assets/e7fbe8f7-511c-4924-81f4-0203e911a359)
all good to go
